In [5]:
import numpy as np

In [6]:
zero10 = np.zeros(10)
zero10

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
a = np.arange(6)
# changing the axis of the array 
a2 = a[np.newaxis,:]
a2.shape

(1, 6)

In [8]:
one10 = np.ones(10)
one10

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
lin5 = np.linspace(5,5,10)
lin5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [10]:
lin = np.linspace(10,50,41)
lin

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49., 50.])

In [11]:
linEven = np.linspace(10,50,21)
linEven

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40., 42., 44., 46., 48., 50.])

In [12]:
arrEven = np.arange(10,52,2)
arrEven

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [13]:
arrTrD = np.arange(0,9).reshape(3,3)
arrTrD

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
id3 = np.ones(9).reshape(3,3)
id3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
rand1 = np.random.rand(1)
rand1

array([0.72785496])

In [16]:
std = arrTrD.std()
std

2.581988897471611